name: Publish Package to Pypi

on:
  push:
    tags:
      - "v*"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: Build and publish on pypi
      env:
        TWINE_USERNAME: "__token__"
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        pip3 install build
        pip3 install twine
        rm -rf dist
        python3 -m build
        python3 -m twine upload --repository pypi dist/* --verbose
